### ISSUE TITLE
Upgrade StructLinq

### ISSUE THREAD

**Issue by aalmada** [NetFabric/LinqBenchmarks#10]
Hi @reegeek 
After a long pause away from OSS development, I'm trying to update the benchmarks.
I tried to upgrade StructLinq but it doesn't compile. The `uint` to `int` changes are easy to fix but I could not figure out what to do with the changes with `Where` and `Select` using `ref`.
Can you please submit a PR or simple give me some pointers?
Thanks

**Comment by reegeek** [comment]
Hi,

I think I could submit a PR today.

Regards
