### ISSUE TITLE
Discussion: Type of T

### ISSUE THREAD

**Issue by reegeek** [NetFabric/LinqBenchmarks#2]
Hi,
Currently, all tests are made on "IEnumerable<int>".
I think benchmark should bench 3 kind of object:
* int (small valueType)
* a class
* fat struct (fat valueType)
Impact on enumeration should be important.

For the moment, I don't know how design it and avoid Copy-Paste between type.

Again, thank for this repository.

**Comment by aalmada** [comment]
Yes, you right. I've been thinking about that too. 
For now, it also only uses arrays, List<>, and Range() as sources. These are very common but there are other sources that have reference-type enumerators, value-type enumerators, indexers, that implement ICollection<> or not. Are there other queries that should be included? There are so many combinations. I'm trying to find a good set of benchmarks without making these unmanageable.
You're all welcome to contribute with ideas and/or code.

**Comment by aalmada** [comment]
@reegeek A class will have similar behavior to the `int`. Isn't it?

**Comment by reegeek** [comment]
For StructLinq there is an impact:
https://github.com/reegeek/StructLinq/blob/v0.19/src/StructLinq.Benchmark/ArrayOfIntSum.cs

https://github.com/reegeek/StructLinq/blob/v0.19/src/StructLinq.Benchmark/ArrayOfClassSum.cs

**Comment by aalmada** [comment]
@reegeek I now added benchmarks for a fat value type but I couldn't figure out how to use `ToRefStructEnumerable` in most of the cases. Can you please submit a PR?

**Comment by reegeek** [comment]
Ok, I will do that.

**Comment by reegeek** [comment]
I think you not finish your work en ValueType benchmarks because all "Sources" are int[] and not FatValueType[]

**Comment by aalmada** [comment]
@reegeek Yes, you're right. 😥 I think it's fixed now.
