### ISSUE TITLE
Big table of comparison

### ISSUE THREAD

**Issue by Happypig375** [NetFabric/LinqBenchmarks#21]
To make the results more useful, consider aggregating all benchmark results into one table in README possibly with ⚪🔴🟠🟡🟢🔵🟣🟤⚫s so that we can immediately see which one is faster in which areas without needing to click many times.

**Comment by aalmada** [comment]
@Happypig375 
The tables are saved automatically to files as they generated by BenchmarkDotNet. I would have to parse the markdown to set the colors. I don't know if I would want to invest that much time in it.
Thanks for the suggestion.
